flags: {}
extra-include-dirs:
- /usr/local/include
extra-package-dbs: []
extra-lib-dirs:
- /usr/local/bin
packages:
- '.'
- ../SPL
extra-deps:
- Stack-0.3.2
- var-0.2.0.0
- z3-4.1.0
resolver: lts-8.0
