name:                ControlFlow
version:             0.1.0.0
github:              "ramyshahin/ControlFlow"
license:             BSD3
author:              "Ramy Shahin"
maintainer:          "r.shahin@computer.org"
copyright:           "Copyright (c) 2020, Ramy Shahin. All rights reserved."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Program Analysis

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ramyshahin/ControlFlow#readme>

dependencies:
- base >= 4.7 && < 5
- graphviz
- language-c
- containers
- text
- SPL
- hashtables
- multimap

library:
  source-dirs: src
  ghc-options:
    - -O2
  dependencies:
  - deepseq

executables:
  ControlFlow-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -rtsopts
#- -with-rtsopts=-N
    dependencies:
    - ControlFlow
    - criterion-measurement
    - criterion
#    - deepseq

tests:
  ControlFlow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ControlFlow
