flags: {}
extra-package-dbs: []
extra-include-dirs: [/usr/local/include]
extra-lib-dirs: [/usr/local/lib]
packages:
- '.'
extra-deps:
- process-1.6.5.0
- cudd-0.1.0.4
- base-4.11.1.0
- c2hs-0.28.6
resolver: lts-13.10
